SELECT
  ws.SET_ID,
  wos.STORAGE_ID,
  wosf.STORAGE_FIELD_ID,
  dc.TABLE_NAME AS STORAGE_LOCAL_TABLE_NAME,
  tc.DB_COLUMN_NAME AS SRC_COLUMN_NAME,
  wosf.COLUMN_FORMAT,
  dcf.FIELD_NAME AS DST_COLUMN_NAME,
  scc.CONFIG_NAME AS DST_COLUMN_TYPE
FROM
  WARNING_OBJECT_STORAGE wos
LEFT JOIN
  WARNING_SET ws
  ON ws.SET_ID = wos.WARNING_SET_ID
LEFT JOIN
  WARNING_OBJECT_STORAGE_FIELD wosf
  ON wos.STORAGE_ID = wosf.STORAGE_ID
LEFT JOIN
  DATA_CONFIG dc
  ON dc.DATA_CONFIG_ID = wos.DATA_CONFIG_ID
LEFT JOIN
  TABLE_COLUMN tc
  ON wosf.TABLE_COLUMN_ID = tc.TABLE_COLUMN_ID
LEFT JOIN
  DATA_CONFIG_FIELD dcf
  ON dcf.FIELD_ID = wosf.FIELD_ID
LEFT JOIN
  SYS_CODE_CONFIG scc
  ON scc.ID = dcf.FIELD_TYPE;