package com.tdl.study.spark.nk

trait TripFieldIdx {
  val VENDORID = 0
  val TPEP_PICKUP_DATETIME = VENDORID + 1
  val TPEP_DROPOFF_DATETIME = TPEP_PICKUP_DATETIME + 1
  val PASSENGER_COUNT = TPEP_DROPOFF_DATETIME + 1
  val TRIP_DISTANCE = PASSENGER_COUNT + 1
  val PICKUP_LONGITUDE = TRIP_DISTANCE + 1
  val PICKUP_LATITUDE = PICKUP_LONGITUDE + 1
  val RATECODEID = PICKUP_LATITUDE + 1
  val STORE_AND_FWD_FLAG = RATECODEID +1
  val DROPOFF_LONGITUDE = STORE_AND_FWD_FLAG + 1
  val DROPOFF_LATITUDE = DROPOFF_LONGITUDE + 1
  val PAYMENT_TYPE = DROPOFF_LATITUDE + 1
  val FARE_AMOUNT = PAYMENT_TYPE + 1
  val EXTRA = FARE_AMOUNT + 1
  val MTA_TAX = EXTRA + 1
  val TIP_AMOUNT = MTA_TAX + 1
  val TOLLS_AMOUNT = TIP_AMOUNT + 1
  val IMPROVEMENT_SURCHARGE = TOLLS_AMOUNT + 1
  val TOTAL_AMOUNT = IMPROVEMENT_SURCHARGE + 1
}
